/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenIndexRouteImport } from './routes/token/index'
import { Route as SurveyIndexRouteImport } from './routes/survey/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as PricingDemoIndexRouteImport } from './routes/pricing-demo/index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DeploymentsIdIndexRouteImport } from './routes/deployments/$id/index'
import { Route as DashboardIdIndexRouteImport } from './routes/dashboard/$id/index'
import { Route as DashboardIdVulnerabilityScannerIndexRouteImport } from './routes/dashboard/$id/vulnerability-scanner/index'
import { Route as DashboardIdReadmeGeneratorIndexRouteImport } from './routes/dashboard/$id/readme-generator/index'
import { Route as DashboardIdPrAnalyzerIndexRouteImport } from './routes/dashboard/$id/pr-analyzer/index'
import { Route as DashboardIdEnvironmentProvisioningIndexRouteImport } from './routes/dashboard/$id/environment-provisioning/index'
import { Route as DashboardIdCodeStructureIndexRouteImport } from './routes/dashboard/$id/code-structure/index'
import { Route as DashboardIdChatWithCodeIndexRouteImport } from './routes/dashboard/$id/chat-with-code/index'
import { Route as DashboardIdAutomatedTestingIndexRouteImport } from './routes/dashboard/$id/automated-testing/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenIndexRoute = TokenIndexRouteImport.update({
  id: '/token/',
  path: '/token/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyIndexRoute = SurveyIndexRouteImport.update({
  id: '/survey/',
  path: '/survey/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingDemoIndexRoute = PricingDemoIndexRouteImport.update({
  id: '/pricing-demo/',
  path: '/pricing-demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DeploymentsIdIndexRoute = DeploymentsIdIndexRouteImport.update({
  id: '/deployments/$id/',
  path: '/deployments/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdIndexRoute = DashboardIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIdVulnerabilityScannerIndexRoute =
  DashboardIdVulnerabilityScannerIndexRouteImport.update({
    id: '/$id/vulnerability-scanner/',
    path: '/$id/vulnerability-scanner/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdReadmeGeneratorIndexRoute =
  DashboardIdReadmeGeneratorIndexRouteImport.update({
    id: '/$id/readme-generator/',
    path: '/$id/readme-generator/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdPrAnalyzerIndexRoute =
  DashboardIdPrAnalyzerIndexRouteImport.update({
    id: '/$id/pr-analyzer/',
    path: '/$id/pr-analyzer/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdEnvironmentProvisioningIndexRoute =
  DashboardIdEnvironmentProvisioningIndexRouteImport.update({
    id: '/$id/environment-provisioning/',
    path: '/$id/environment-provisioning/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdCodeStructureIndexRoute =
  DashboardIdCodeStructureIndexRouteImport.update({
    id: '/$id/code-structure/',
    path: '/$id/code-structure/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdChatWithCodeIndexRoute =
  DashboardIdChatWithCodeIndexRouteImport.update({
    id: '/$id/chat-with-code/',
    path: '/$id/chat-with-code/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdAutomatedTestingIndexRoute =
  DashboardIdAutomatedTestingIndexRouteImport.update({
    id: '/$id/automated-testing/',
    path: '/$id/automated-testing/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/pricing-demo/': typeof PricingDemoIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/survey/': typeof SurveyIndexRoute
  '/token/': typeof TokenIndexRoute
  '/dashboard/$id/': typeof DashboardIdIndexRoute
  '/deployments/$id/': typeof DeploymentsIdIndexRoute
  '/dashboard/$id/automated-testing/': typeof DashboardIdAutomatedTestingIndexRoute
  '/dashboard/$id/chat-with-code/': typeof DashboardIdChatWithCodeIndexRoute
  '/dashboard/$id/code-structure/': typeof DashboardIdCodeStructureIndexRoute
  '/dashboard/$id/environment-provisioning/': typeof DashboardIdEnvironmentProvisioningIndexRoute
  '/dashboard/$id/pr-analyzer/': typeof DashboardIdPrAnalyzerIndexRoute
  '/dashboard/$id/readme-generator/': typeof DashboardIdReadmeGeneratorIndexRoute
  '/dashboard/$id/vulnerability-scanner/': typeof DashboardIdVulnerabilityScannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/pricing-demo': typeof PricingDemoIndexRoute
  '/signup': typeof SignupIndexRoute
  '/survey': typeof SurveyIndexRoute
  '/token': typeof TokenIndexRoute
  '/dashboard/$id': typeof DashboardIdIndexRoute
  '/deployments/$id': typeof DeploymentsIdIndexRoute
  '/dashboard/$id/automated-testing': typeof DashboardIdAutomatedTestingIndexRoute
  '/dashboard/$id/chat-with-code': typeof DashboardIdChatWithCodeIndexRoute
  '/dashboard/$id/code-structure': typeof DashboardIdCodeStructureIndexRoute
  '/dashboard/$id/environment-provisioning': typeof DashboardIdEnvironmentProvisioningIndexRoute
  '/dashboard/$id/pr-analyzer': typeof DashboardIdPrAnalyzerIndexRoute
  '/dashboard/$id/readme-generator': typeof DashboardIdReadmeGeneratorIndexRoute
  '/dashboard/$id/vulnerability-scanner': typeof DashboardIdVulnerabilityScannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/pricing-demo/': typeof PricingDemoIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/survey/': typeof SurveyIndexRoute
  '/token/': typeof TokenIndexRoute
  '/dashboard/$id/': typeof DashboardIdIndexRoute
  '/deployments/$id/': typeof DeploymentsIdIndexRoute
  '/dashboard/$id/automated-testing/': typeof DashboardIdAutomatedTestingIndexRoute
  '/dashboard/$id/chat-with-code/': typeof DashboardIdChatWithCodeIndexRoute
  '/dashboard/$id/code-structure/': typeof DashboardIdCodeStructureIndexRoute
  '/dashboard/$id/environment-provisioning/': typeof DashboardIdEnvironmentProvisioningIndexRoute
  '/dashboard/$id/pr-analyzer/': typeof DashboardIdPrAnalyzerIndexRoute
  '/dashboard/$id/readme-generator/': typeof DashboardIdReadmeGeneratorIndexRoute
  '/dashboard/$id/vulnerability-scanner/': typeof DashboardIdVulnerabilityScannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/'
    | '/deployments/'
    | '/pricing-demo/'
    | '/signup/'
    | '/survey/'
    | '/token/'
    | '/dashboard/$id/'
    | '/deployments/$id/'
    | '/dashboard/$id/automated-testing/'
    | '/dashboard/$id/chat-with-code/'
    | '/dashboard/$id/code-structure/'
    | '/dashboard/$id/environment-provisioning/'
    | '/dashboard/$id/pr-analyzer/'
    | '/dashboard/$id/readme-generator/'
    | '/dashboard/$id/vulnerability-scanner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/deployments'
    | '/pricing-demo'
    | '/signup'
    | '/survey'
    | '/token'
    | '/dashboard/$id'
    | '/deployments/$id'
    | '/dashboard/$id/automated-testing'
    | '/dashboard/$id/chat-with-code'
    | '/dashboard/$id/code-structure'
    | '/dashboard/$id/environment-provisioning'
    | '/dashboard/$id/pr-analyzer'
    | '/dashboard/$id/readme-generator'
    | '/dashboard/$id/vulnerability-scanner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/'
    | '/deployments/'
    | '/pricing-demo/'
    | '/signup/'
    | '/survey/'
    | '/token/'
    | '/dashboard/$id/'
    | '/deployments/$id/'
    | '/dashboard/$id/automated-testing/'
    | '/dashboard/$id/chat-with-code/'
    | '/dashboard/$id/code-structure/'
    | '/dashboard/$id/environment-provisioning/'
    | '/dashboard/$id/pr-analyzer/'
    | '/dashboard/$id/readme-generator/'
    | '/dashboard/$id/vulnerability-scanner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  PricingDemoIndexRoute: typeof PricingDemoIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  SurveyIndexRoute: typeof SurveyIndexRoute
  TokenIndexRoute: typeof TokenIndexRoute
  DeploymentsIdIndexRoute: typeof DeploymentsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/': {
      id: '/token/'
      path: '/token'
      fullPath: '/token/'
      preLoaderRoute: typeof TokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/': {
      id: '/survey/'
      path: '/survey'
      fullPath: '/survey/'
      preLoaderRoute: typeof SurveyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-demo/': {
      id: '/pricing-demo/'
      path: '/pricing-demo'
      fullPath: '/pricing-demo/'
      preLoaderRoute: typeof PricingDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/deployments/$id/': {
      id: '/deployments/$id/'
      path: '/deployments/$id'
      fullPath: '/deployments/$id/'
      preLoaderRoute: typeof DeploymentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id/': {
      id: '/dashboard/$id/'
      path: '/$id'
      fullPath: '/dashboard/$id/'
      preLoaderRoute: typeof DashboardIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id/vulnerability-scanner/': {
      id: '/dashboard/$id/vulnerability-scanner/'
      path: '/$id/vulnerability-scanner'
      fullPath: '/dashboard/$id/vulnerability-scanner/'
      preLoaderRoute: typeof DashboardIdVulnerabilityScannerIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id/readme-generator/': {
      id: '/dashboard/$id/readme-generator/'
      path: '/$id/readme-generator'
      fullPath: '/dashboard/$id/readme-generator/'
      preLoaderRoute: typeof DashboardIdReadmeGeneratorIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id/pr-analyzer/': {
      id: '/dashboard/$id/pr-analyzer/'
      path: '/$id/pr-analyzer'
      fullPath: '/dashboard/$id/pr-analyzer/'
      preLoaderRoute: typeof DashboardIdPrAnalyzerIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id/environment-provisioning/': {
      id: '/dashboard/$id/environment-provisioning/'
      path: '/$id/environment-provisioning'
      fullPath: '/dashboard/$id/environment-provisioning/'
      preLoaderRoute: typeof DashboardIdEnvironmentProvisioningIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id/code-structure/': {
      id: '/dashboard/$id/code-structure/'
      path: '/$id/code-structure'
      fullPath: '/dashboard/$id/code-structure/'
      preLoaderRoute: typeof DashboardIdCodeStructureIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id/chat-with-code/': {
      id: '/dashboard/$id/chat-with-code/'
      path: '/$id/chat-with-code'
      fullPath: '/dashboard/$id/chat-with-code/'
      preLoaderRoute: typeof DashboardIdChatWithCodeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id/automated-testing/': {
      id: '/dashboard/$id/automated-testing/'
      path: '/$id/automated-testing'
      fullPath: '/dashboard/$id/automated-testing/'
      preLoaderRoute: typeof DashboardIdAutomatedTestingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardIdIndexRoute: typeof DashboardIdIndexRoute
  DashboardIdAutomatedTestingIndexRoute: typeof DashboardIdAutomatedTestingIndexRoute
  DashboardIdChatWithCodeIndexRoute: typeof DashboardIdChatWithCodeIndexRoute
  DashboardIdCodeStructureIndexRoute: typeof DashboardIdCodeStructureIndexRoute
  DashboardIdEnvironmentProvisioningIndexRoute: typeof DashboardIdEnvironmentProvisioningIndexRoute
  DashboardIdPrAnalyzerIndexRoute: typeof DashboardIdPrAnalyzerIndexRoute
  DashboardIdReadmeGeneratorIndexRoute: typeof DashboardIdReadmeGeneratorIndexRoute
  DashboardIdVulnerabilityScannerIndexRoute: typeof DashboardIdVulnerabilityScannerIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardIdIndexRoute: DashboardIdIndexRoute,
  DashboardIdAutomatedTestingIndexRoute: DashboardIdAutomatedTestingIndexRoute,
  DashboardIdChatWithCodeIndexRoute: DashboardIdChatWithCodeIndexRoute,
  DashboardIdCodeStructureIndexRoute: DashboardIdCodeStructureIndexRoute,
  DashboardIdEnvironmentProvisioningIndexRoute:
    DashboardIdEnvironmentProvisioningIndexRoute,
  DashboardIdPrAnalyzerIndexRoute: DashboardIdPrAnalyzerIndexRoute,
  DashboardIdReadmeGeneratorIndexRoute: DashboardIdReadmeGeneratorIndexRoute,
  DashboardIdVulnerabilityScannerIndexRoute:
    DashboardIdVulnerabilityScannerIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  PricingDemoIndexRoute: PricingDemoIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  SurveyIndexRoute: SurveyIndexRoute,
  TokenIndexRoute: TokenIndexRoute,
  DeploymentsIdIndexRoute: DeploymentsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
